version: "3.9"

services:
  server2:
    build:
      context: ./server2
      dockerfile: Dockerfile
    container_name: grpc_server
    ports:
      - "50051:50051"
    networks:
      - app_network

  server1:
    build:
      context: ./server1
      dockerfile: Dockerfile
    container_name: gin_http_server
    ports:
      - "8081:8080"
    depends_on:
      - server2
    networks:
      - app_network
    environment:
      GRPC_SERVER_ADDRESS: "grpc_server:50051"

networks:
  app_network:
    driver: bridge
