version: '3.8'

services:
  my-go-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - shared-network  # Use a unified network name for connectivity
    ports:
      - "8080:8080"  # Expose the application port

networks:
  shared-network:
    driver: bridge  # Use a shared network to allow communication with other services
